name: GitHub Pages

on:
  pull_request:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Build
        run: npm ci
        # 静的HTMLを生成するためには generate での実行が必要
      - run: npm run generate